apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "no-trigger-websocket-chat", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: websocket-pipeline
  name: websocket-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
            stage 'build'
            openshiftBuild(buildConfig: 'no-trigger-websocket-chat', showBuildLogs: 'true')

            stage 'deploy'
            openshiftDeploy(deploymentConfig: 'no-trigger-websocket-chat')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: CzgPZAZ5m2
    type: GitHub
  - generic:
      secret: CzgPZAZ5m2
    type: Generic
